# Conexión a PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://[HOST_DE_SUPABASE]:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=[bryCompany420!]
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
# Usamos 'validate' porque ustedes ya crearon las tablas con el script SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=cochi-backend
