# ==============================================================
# Valores por defecto para desarrollo local (Terminal / VS Code)
# Nota: Al correr en Docker, el docker-compose sobreescribirá 
# esto inyectando las variables del archivo .env automáticamente.
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ferreteria_db
spring.datasource.username=postgres
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=ferreteria-backend